---
- name: add default nginx.conf
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
  - reload nginx
