---
- name: start jenkins
  service:
    name: jenkins
    state: started
    enabled: yes
  become: true

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  listen: reload nginx
  become: true

- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  become: true
